# Write a program to create a dictionary of Englaish words with values as their Bengali translation. Provide user with an option to look it up!

english_dictionary = {
    "I": "আমি",
    "You": "তুমি",
    "He/She": "সে",
    "We": "আমরা",
    "They": "তারা",
    "Book": "বই",
    "Pen": "কলম",
    "Notebook": "খাতা",
    "School": "স্কুল",
    "Teacher": "শিক্ষক",
    "Student": "ছাত্র",
    "Friend": "বন্ধু",
    "House": "বাড়ি",
    "Door": "দরজা",
    "Window": "জানালা",
    "Water": "পানি",
    "Food": "খাবার",
    "Rice": "ভাত",
    "Fruit": "ফল",
    "Flower": "ফুল",
    "Tree": "গাছ",
    "Bird": "পাখি",
    "Cat": "বিড়াল",
    "Dog": "কুকুর",
    "Sun": "সূর্য",
    "Moon": "চাঁদ",
    "Sky": "আকাশ",
    "River": "নদী",
    "Sea": "সমুদ্র",
    "Mountain": "পাহাড়",
    "Red": "লাল",
    "Blue": "নীল",
    "Green": "সবুজ",
    "Black": "কালো",
    "White": "সাদা",
    "Big": "বড়",
    "Small": "ছোট",
    "Good": "ভালো",
    "Bad": "খারাপ",
    "Beautiful": "সুন্দর",
    "Fast": "দ্রুত",
    "Slow": "ধীর",
    "Day": "দিন",
    "Night": "রাত",
    "Morning": "সকাল",
    "Afternoon": "বিকাল",
    "Today": "আজ",
    "Tomorrow": "আগামীকাল",
    "Yesterday": "গতকাল",
    "Thank you": "ধন্যবাদ"
}

word = input(" Enter the word you want the meaning of:").capitalize()

print(english_dictionary[word])